Backoffice &raquo; Visitas &raquo; Adicionar Poi ao percurso 

<style>
input {min-width:300px;max-width:100%;}

</style>

 <?php
 $title = 'Adicionar Poi ao percurso';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('percurso',array('action' => 'addPoiPercurso','id' => $this->id)));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('Order'));
 echo $this->formRow($form->get('Hour'));
 echo $this->formRow($form->get('RunTime'));
 echo $this->formRow($form->get('pois'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();