Backoffice &raquo; Visitas &raquo; Edição do Percurso da Visita 

<style>
input {min-width:300px;max-width:100%;}

</style>

 <?php
 $title = 'Editar Percurso da Visita';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('percurso',array('action' => 'edit','id' => $this->id)));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('pontos'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();