 <?php
 $title = 'Iniciar sessão';
 $this->headTitle($title);
 ?>
 <div class="zonalogin">
 <h2><?php echo $this->escapeHtml($title); ?></h2>
<?php
 $form->setAttribute('action', $this->url('turistas', array('action' => 'login')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('email'));
 echo $this->formRow($form->get('password'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 </div>
 <?php
 
 
 