<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TukPorto\Module'                        => __DIR__ . '/Module.php',
    'TukPorto\Controller\PercursoController' => __DIR__ . '/src/TukPorto/Controller/PercursoController.php',
    'TukPortoTest\Framework\TestCase'        => __DIR__ . '/tests/TukPorto/Framework/TestCase.php',
    'TukPortoTest\SampleTest'                => __DIR__ . '/tests/TukPorto/SampleTest.php',
);
